### ISSUE TITLE
Add documentations

### ISSUE THREAD

**Issue by ykzts** [ykzts/ruboty-discord#4]
- [x] Improve README (#6)
- [x] Add Contribution guide (#7)
- [x] Add Code of Contact (#8)
- [x] Add Issue template (#9)
- ~~Add Pull Request template~~

**Comment by ykzts** [comment]
done.
